name: Build X96 Mate Armbian

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Armbian
        uses: actions/checkout@v4
        with:
          repository: armbian/build
          path: armbian
          fetch-depth: 1

      - name: Free disk space
        run: |
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/hostedtoolcache
          sudo docker system prune -af || true
          df -h

      - name: Build image
        working-directory: armbian
        run: |
          sudo ./compile.sh requirements
          sudo chown -R $USER:$USER .
          ./compile.sh build \
            BOARD=x96-mate \
            BRANCH=current \
            RELEASE=trixie \
            BUILD_MINIMAL=yes \
            BUILD_DESKTOP=no \
            KERNEL_CONFIGURE=no \
            COMPRESS_OUTPUTIMAGE=xz \
            EXPERT=yes

      - name: Show result
        run: |
          echo "=== OUTPUT IMAGES ==="
          ls -lah armbian/output/images/
          find armbian/output/images -maxdepth 1 -type f

      - name: Upload image
        uses: actions/upload-artifact@v4
        with:
          name: x96-mate-armbian
          path: |
            armbian/output/images/*.img.xz
            armbian/output/images/*.sha
          if-no-files-found: error
